name: Lint, Build Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Build
      run: npm run build